// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBmL-KaTk-ufJlp6_bxAUF_lsH8_94Yzc',
    appId: '1:726766495521:web:ee2cbed11d4af44dcf8060',
    messagingSenderId: '726766495521',
    projectId: 'pos-software-ef89c',
    authDomain: 'pos-software-ef89c.firebaseapp.com',
    databaseURL: 'https://pos-software-ef89c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-software-ef89c.firebasestorage.app',
    measurementId: 'G-9S9GGMDX9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAKQhJhFEF5mTNcIIBYa8YtEjNuEAR5L0',
    appId: '1:726766495521:android:3814b5c693ee48d0cf8060',
    messagingSenderId: '726766495521',
    projectId: 'pos-software-ef89c',
    databaseURL: 'https://pos-software-ef89c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-software-ef89c.firebasestorage.app',
  );
}
